### ISSUE TITLE
Error with using 'reply' in the on :message block

### ISSUE THREAD

**Issue by koonwah** [exciting-io/slack-bot-server#19]
Hi,

I got an error when I try to use the on :message hook.

```
I, [2016-03-30T01:46:44.693127 #2228]  INFO -- : [BOT/bot] {:error=>#<NoMethodError: undefined method `[]' for nil:NilClass>}
I, [2016-03-30T01:46:44.693604 #2228]  INFO -- : [BOT/bot] {:backtrace=>["/Users/K/.rvm/gems/ruby-2.2.1/gems/slack-bot-server-0.4.2/lib/slack_bot_server/bot.rb:116:in `reply'",
```

Inside my bot class, I did this:

```
  on(:message) do |data|
    reply text: "Hello."
  end
```

It looks like the @last_received_data in the reply method (line 116 in bot.rb) is nil for some reason. Any idea what's wrong here?

**Comment by koonwah** [comment]
It looks like the problem is because _on :message_ is not doing what the other hook: _on_mention_ is doing:

```
@last_received_data = data.merge('message' => message)
          instance_exec(@last_received_data, &block)
```

Hence @last_received_data is never set, causing the error. But that's just my guess. Would you look into this?

**Comment by lazyatom** [comment]
Can you explain a little more about what you're trying to actually achieve? The `on(:message)` handler will get called for *every message* the bot receives - do you really want it to send a reply to every one?

**Comment by lazyatom** [comment]
It's also worth bearing in mind that `on(:message)` is quite a low-level callback, which gets invoked for lots of events - even for messages that your bot has sent. I've just pushed a new version (0.4.4) which should allow you to do this, but please take careful note of the caveats - see commit https://github.com/exciting-io/slack-bot-server/commit/c6ff1c9d045b0aeffca8fac2fb06ea867f15ade4

**Comment by lazyatom** [comment]
Hopefully the changes I made resolve your problem; feel free to re-open if you're still having problems.
