### ISSUE TITLE
Error w/ slack-api gem's faye-websocket dependency

### ISSUE THREAD

**Issue by LucasCioffi** [exciting-io/slack-bot-server#2]
I got this gemfile conflict:

    slack-bot-server (>= 0) ruby depends on
        slack-api (>= 1.1) ruby depends on
            faye-websocket (~> 0.9.2) ruby
  
    slack-ruby-client (>= 0) ruby depends on
        faye-websocket (0.10.1)

I forked the slack-ruby gem at https://github.com/LucasCioffi/slack-ruby-gem/blob/dev/slack.gemspec and changed the faye dependency:

    "faye-websocket", ">= 0.9.2"

I tried including this fork of the slack-ruby gem into my fork of slack-bot-server at https://github.com/LucasCioffi/slack-bot-server/blob/master/slack_bot_server.gemspec but this format didn't work for specifying the git source: 

    spec.add_dependency "slack-api", :git => "https://github.com/LucasCioffi/slack-ruby-gem"

...so then I commented it out and manually included the files in this order in my gemfile:

    gem "slack-api", :git => "https://github.com/LucasCioffi/slack-ruby-gem"
    gem 'slack-bot-server', :git => 'https://github.com/LucasCioffi/slack-bot-server'

The error is gone, but this is a suboptimal solution.  Anything else that can be done?

**Comment by lazyatom** [comment]
Hi Lucas,

Let's see if we can get you going. A few questions:

* Which version of Ruby are you using?
* Are you able to share your whole Gemfile with me?

I've just tried bundling version `0.1.2` in an otherwise-empty Gemfile, and it works OK:

```shell
➜ /tmp $ mkdir test
➜ /tmp $ cd test
➜ test $ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
➜ test $ bundle --version
Bundler version 1.10.6
➜ test $ echo "source 'https://rubygems.org'\n\ngem 'slack-bot-server'" > Gemfile
➜ test $ bundle install
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Installing eventmachine 1.0.8 with native extensions
Installing multipart-post 2.0.0
Installing faraday 0.9.2
Installing faraday_middleware 0.10.0
Installing websocket-extensions 0.1.2
Installing websocket-driver 0.6.3 with native extensions
Installing faye-websocket 0.9.2
Installing multi_json 1.11.2
Installing slack-api 1.2.0
Installing slack-bot-server 0.1.2
Using bundler 1.10.6
Bundle complete! 1 Gemfile dependency, 11 gems now installed.
Bundled gems are installed into ./.bundle/gems.
```

**Comment by LucasCioffi** [comment]
The issue is no longer happening after emptying the bundle like this:

    $rvm gemset empty test_project
    $bundle install

Thank you for looking into it.
