### ISSUE TITLE
Not able to catch team join event

### ISSUE THREAD

**Issue by anjain** [exciting-io/slack-bot-server#20]
Hi,

Not able to catch team join event on(:team_join). Can You please help me

**Comment by lazyatom** [comment]
I'm not familiar with the `team_join` event - can you show me the documentation for it?

**Comment by anjain** [comment]
Please see this https://api.slack.com/events/team_join

**Comment by anjain** [comment]
Please help me :)

**Comment by lazyatom** [comment]
I've just released v0.4.6 which adds a new `on_slack_event` callback hook that should let you listen to these events. For example

```ruby
class SampleBot < SlackBotServer::Bot
  username 'SampleBot'
  
  on_slack_event :team_join` do |data|
    # handle the data
  end
end
```

It's worth mentioning that 0.4.3 onwards use an upgraded version of the underlying `Slack` ruby client which also listens to this event and uses it to manage the underlying store of users present in the team; if you were hoping to use this event purely to update some list of connected users, and *not* for any interaction, then you might be able to avoid the callback and just use `client.users` to get the current list of connected users.

Let me know if this works OK for you!

**Comment by anjain** [comment]
Not work. Not able to catch this event when user join the team

**Comment by lazyatom** [comment]
Are you able to share the source code of your bot with me, either here or
privately over email?  
  
\--

James

  

On Mar 31 2016, at 2:06 pm, anjain <notifications@github.com> wrote:  

> Not work. Not able to catch this event when user join the team

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com
/exciting-io/slack-bot-server/issues/20#issuecomment-203928551)![](https://git
hub.com/notifications/beacon/AAAAkY4192atfebJS9NIHiXxKTQLB6ueks5py8a4gaJpZM4H8
mq_.gif)

**Comment by anjain** [comment]
> below is bin slack_server file code


require 'slack_bot_server'
require 'slack_bot_server/redis_queue'
queue = SlackBotServer::RedisQueue.new

server = SlackBotServer::Server.new(queue: queue)


server.on_add do |token|
  Bot.new(token: token)
end
server.add_bot(ENV['SLACK_BOT_TOKEN'])
server.start


> and Bot code is

require 'slack_bot_server/bot'

class Bot < SlackBotServer::Bot
	on(:message) do |data|
    	Rails.logger.debug data
    end

    on_slack_event :team_join do |data|
    	Rails.logger.debug data
    	# handle the data
    end
end

> i am able to catch the on :message event but not on_slack_event :team_join

**Comment by anjain** [comment]
Any update here

**Comment by lazyatom** [comment]
I'll try to look at this in the next couple of days; what's problematic is that I think the only way to test this event is by creating new team members, which requires a bit of work to set up in a way that doesn't cost me a bunch of money :) (unless you know of an easier way of testing it, in which case please do let me know!)

**Comment by anjain** [comment]
Suppose i have a team in slack xyz and i send my team invitation to someone email then when he join the team we should be able to catch that event at this time i am not able to do so.

**Comment by anjain** [comment]
@lazyatom any update here

**Comment by anjain** [comment]
@lazyatom got the team_join event working

**Comment by lazyatom** [comment]
For the benefit of others, what did you need to do to get it working?
