### ISSUE TITLE
Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by anjain** [exciting-io/slack-bot-server#21]
queue = SlackBotServer::RedisQueue.new(redis: Redis.new)
slack_remote = SlackBotServer::RemoteControl.new(queue: queue)
slack_remote.add_bot('user-accounts-slack-api-token')

`when i try to add_bot then above error comes on heroku but it is working fine in local please help`

**Comment by lazyatom** [comment]
It's likely that you'll need to specifically configure your Redis connection via the environment variables (i.e. `REDIS_URL`) that Heroku's Redis integration gives you:

```ruby
queue = SlackBotServer::RedisQueue.new(redis: Redis.new(url: ENV['REDIS_URL']))
```

**Comment by anjain** [comment]
Thanks man :)
