### ISSUE TITLE
Failing test in circleci

### ISSUE THREAD

**Issue by anjain** [exciting-io/slack-bot-server#22]
when i run rspec error comes
![slackbotserver_circle_ci_error](https://cloud.githubusercontent.com/assets/633566/14318246/98567a16-fc29-11e5-8863-fdf5e67a5593.png)

**Comment by anjain** [comment]
def initialize(token:, key: nil)
    @token = token
    @key = key || @token
    @connected = false
    @running = false
  end

i think we getting this error due to token:,

**Comment by lazyatom** [comment]
Which version of Ruby are you using? From your screenshot, it looks like you're using Ruby 2.0; is upgrading to 2.1 (or 2.2 or 2.3) an option? Those are the versions we test against.

**Comment by anjain** [comment]
Thanks when i change the version it works
