### ISSUE TITLE
Gaps in the README

### ISSUE THREAD

**Issue by gabeodess** [exciting-io/slack-bot-server#23]
After a bit of messing around I was finally able to get this working.  A few things that seem to be missing in the documentation/README:

 - I had to manually require the library in my gemfile `gem 'slack-bot-server', :require => 'slack_bot_server'`

 - It looks like the library is dependent on the redis gem, but not included in the libraries Gemfile so I needed to add that to my Gemfile as well `gem 'redis'`

 - in order to access the remote control library I had to first manually require it `require 'slack_bot_server/remote_control'`

 - in order to retrieve a bot token I need to include the `bot` scope when authenticating with Slack

 - in order to send messages from my bot I need to include the `chat:bot:write` scope

 - in order to use the remote control `say` feature I needed to provide a channel with `:channel => 'some-channel-name'`

**Comment by lazyatom** [comment]
Thanks for this! I'll improve the code and/or README as appropriate :)
