### ISSUE TITLE
Extend docs to explain how to use an Add to Slack button with slack-bot-server

### ISSUE THREAD

**Issue by contentfree** [exciting-io/slack-bot-server#26]
The docs have a brief passage re: creating a Slack App, but it doesn't provide hints on what needs to be added to our applications to get an Add to Slack button to work. The docs of slack-bot-server don't seem to explain from _where_ we're supposed to get team tokens.

Presumably we'd need an endpoint in our greater application where the auth code can be posted and then use a `Slack::Web::Client#oauth_access` to get the token.

(BTW, `slack-ruby-bot-server` has this built-in … but it's dependencies on Mongo make it a non-starter – I know they're trying to abstract that out though)

**Comment by spencerldixon** [comment]
+1 for this, does anyone have any idea where to start? Happy to try and give this a shot

**Comment by lazyatom** [comment]
Hi folks,

Sorry about the enormous delay responding to this! I've added some more information to the README - let me know if that helps/doesn't help!
