### ISSUE TITLE
Question about slack-bot-server on Heroku

### ISSUE THREAD

**Issue by LucasCioffi** [exciting-io/slack-bot-server#4]
If this is the Procfile in a Rails app on Heroku...

    web: bundle exec puma -C config/puma.rb
    worker: bundle exec rake jobs:work
    slack_server: bundle exec rails runner bin/slack_server

...then for every Heroku Dyno that spins up, it will have a slack-bot-server instance too, I believe.  Is that redundant because there will be multpile slack-bot-servers monitoring each of the Slack teams?

I guess I could stand up slack-bot-server on its own dyno as a separate app, but I'd like to keep it connected to the main Rails app.  Any other suggestions?

**Comment by lazyatom** [comment]
I think if you follow [Heroku's guidelines about scaling processes](https://devcenter.heroku.com/articles/procfile#scaling-a-process-type) by using `heroku ps:scale`, you can control which processes get run on multiple dynos.
