### ISSUE TITLE
I'm having to repeat the RemoteControl.new command in the console

### ISSUE THREAD

**Issue by LucasCioffi** [exciting-io/slack-bot-server#5]
I'm able to successfully add a bot to the server and broadcast a message using slack_remote from the console, however I always get an error the first time I use this command in the console:
```slack_remote = SlackBotServer::RemoteControl.new(queue: queue)```  

This is not a critical problem, and it may not be related to the gem.  If I repeat the command immediately after it failed, then it works.  Here's the console output showing it working:

    $ require 'slack_bot_server'
      => true
    $ reload!
      Reloading...
      => true 
    $ queue = SlackBotServer::RedisQueue.new(Redis.new)
      => #<SlackBotServer::RedisQueue:0x007ff6b3278b50 @key="slack_bot_server:queue", @redis=#<Redis client v3.2.2 for redis://127.0.0.1:6379/0>> 
    $ slack_remote = SlackBotServer::RemoteControl.new(queue: queue)
      LoadError: Unable to autoload constant RemoteControl, expected     /Users/lucas/Desktop/ruby/bb2/app/models/remote_control.rb to define it
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:495:in `load_missing_constant'
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:526:in `load_missing_constant'
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
      from (irb):4
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
      from /Users/lucas/.rvm/gems/ruby-2.2.0@qiqo/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
      from bin/rails:4:in `require'
      from bin/rails:4:in `<main>'
    $ slack_remote = SlackBotServer::RemoteControl.new(queue: queue)
      => #<SlackBotServer::RemoteControl:0x007ff6b3b895c8 @queue=#<SlackBotServer::RedisQueue:0x007ff6b3278b50 @key="slack_bot_server:queue", @redis=#<Redis client v3.2.2 for redis://127.0.0.1:6379/0>>> 
    $ slack_remote.add_token('the-token-goes-here')
      => 1
    $ slack_remote.say('the-token-goes-here', text: 'I have an important announcement to make!')
      => 1

Having to repeat the command is not what I'd expect.  Does this indicate that anything is wrong with the gem or with how I've set up this app?  

In case it's helpful, here's `remote_control.rb`:

```
class SlackBotServer::RemoteControl
  def initialize(queue:)
    @queue = queue
  end

  def add_token(token)
    @queue.push([:add_token, token])
  end

  def remove_bot(key)
    @queue.push([:remove_bot, key])
  end

  def broadcast(key, message_data)
    @queue.push([:broadcast, key, message_data])
  end

  def say(key, message_data)
    @queue.push([:say, key, message_data])
  end

  def say_to(key, user_id, message_data)
    @queue.push([:say_to, key, user_id, message_data])
  end

  def call(key, method, args)
    @queue.push([:call, [key, method, args]])
  end
end
```

**Comment by lazyatom** [comment]
Is what you've pasted above the contents of your file `app/models/remote_control.rb`? I'm not sure why you created that; it should be provided within the `slack-bot-server` gem...

**Comment by lazyatom** [comment]
Closing this; please do re-open if you're still experiencing problems though.
